### ISSUE TITLE
autofill background color change

### ISSUE THREAD

**Issue by kang-heewon** [splitz-dev/cielmusic-frontend#3]
when using chrome autofill, background color changed to blue.
i hate this.

please use this css
```css
input:-internal-autofill-selected,
input:-webkit-autofill,
input:-webkit-autofill:hover, 
input:-webkit-autofill:focus, 
input:-webkit-autofill:active  {
    background: transparent;
}
```
